spring:
  datasource:
    url: jdbc:mysql://localhost:6606/wigell_padel_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9584/realms/PadelRealm
          audiences: spring-app, account

  keycloak:
    server-url: http://localhost:9584
    realm: PadelRealm

  keycloak.admin:
    realm: PadelRealm
    client-id: spring-app-admin
    client-secret: 8MU6EBGSG6mB7DNYn9YUlhuR3goDuo8K


management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

server:
  port: 8584

logging:
  level:
    root: INFO
    com.strom.wigellPadel: DEBUG

converter:
  service:
    url: http://localhost:8700/api/convert
internal:
  api:
    key: 123456789
