server:
  port: 8583

spring:
  application:
    name: cinema

  datasource:
    url: jdbc:mysql://localhost:6606/wigell_cinema_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8590/realms/cinema_keycloak"

  jackson:
    mapper:
      accept-case-insensitive-enums: true

logging:
  file:
    name: logs/cinema.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
  level:
    root: INFO
    com.sebbe.cinema.services: DEBUG
    com.sebbe.cinema.controllers: ERROR
    org.springframework: INFO

keycloak:
  server-url: http://localhost:8590
  realm: cinema_keycloak

keycloak.admin:
  realm: cinema_keycloak
  client-id: spring-app-admin
  client-secret: P4mi2b1oo34gNxk832MNQR24KjksJhrP

currency:
  api:
    url: http://localhost:8700/api/convert
  api-key: 123456789