services:
  mysql:
    image: mysql:8.0
    container_name: wigell-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wigell_mc_db
      MYSQL_USER: mcuser
      MYSQL_PASSWORD: mcpass
    ports:
      - "6666:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HTTP_PORT: 8081
      KC_PROXY: edge
    ports:
      - "8081:8081"
    depends_on:
      - mysql

volumes:
  mysql_data:
