services:
  mysql:
    image: mysql:8.0
    container_name: wigell-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wigell_mc_db
      MYSQL_USER: mcuser
      MYSQL_PASSWORD: mcpass
    ports:
      - "6666:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:
