server:
  port: 8080

spring:
  application:
    name: api-gateway

  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:8080

  cloud:
    gateway:
      routes:
        - id: padel-service
          uri: http://localhost:8584
          predicates:
            - Path=/padel/**
          filters:
            - StripPrefix=1
        - id: cinema-service
          uri: http://localhost:8583
          predicates:
            - Path=/cinema/**
          filters:
            - StripPrefix=1


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8590/realms/keycloak"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
