server:
  port: 8080

spring:
  application:
    name: api-gateway

  boot:
    admin:
      client:
        url: http://localhost:9090

  cloud:
    gateway:
      routes:


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8590/realms/keycloak"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
