server:
  port: 8585

spring:
  datasource:
    url: jdbc:mysql://localhost:6606/wigell_mc_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8590/realms/keycloak"

  keycloak:
    server-url: http://localhost:8590/realms/keycloak
    realm: keycloak

  keycloak.admin:
    realm: keycloak
    client-id: mc-admin
    client-secret: K7jn3q9pp56hTyz214LMVW89XrtsFguJ

  application:
    name: WigellMC

  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:8585

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/wigell-mc-rental.log
  level:
    root: INFO
    com.andreas.wigellmcrental: DEBUG

converter:
  service:
    url: http://localhost:8700/api/convert

internal:
  api:
    key: 123456789
