server:
  port: 8700
spring:
  application:
    name: converter_microservice
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:8700

internal:
  api:
    key: 123456789

currency:
  api:
    url: https://open.er-api.com/v6/latest/SEK

management:
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /actuator
  endpoint:
    health:
      show-details: always